Repository johnklee/fpu, pull requests merged in 2023-10, with the labels that each got.

#50 Add Ci build
  .github/workflows/ci-build.yml
  .travis.yml
Labels: enhancement, testing, task

#51 fix #47
  fpu/flist.py
Labels: bug

#49 Add many tests and fix bugs to meet 90% coverage
  fpu/fp.py
  pyproject.toml
  tests/unit/test_flist.py
  tests/unit/test_fp.py
Labels: bug, testing

#63 Implement #57 to support parameterized test cases
  .github/workflows/ci-build.yml
  README.md
  tests/__init__.py
  tests/unit/__init__.py
  tests/unit/parameterized.py
  tests/unit/test_flist.py
  tests/unit/test_fp.py
Labels: enhancement, testing

#66 Implement #21
  docs/demo_cases.ipynb
  fpu/flist.py
  tests/unit/test_flist.py
Labels: feature, show case
