Repository johnklee/fpu, pull requests merged in 2023-09, with the labels that each got.

#31 Implement #30 to support `zip` method in `flist.List`
  docs/demo_cases.ipynb
  fpu/flist.py
  tests/unit/test_flist.py
Labels: feature

#42 replace `pytest-lineno` and `pytest-cov` to `coverage` package, with more supports
  Makefile
  pyproject.toml
  requirements.txt
Labels: testing

#46 Implement #45 to add Leetcode problem `905. Sort Array By Parity` into show cases
  docs/demo_cases.ipynb
  fpu/flist.py
  tests/unit/test_flist.py
Labels: show case
